version: "3.8"
services:
  postgres:
    image: "postgres:16.1"
    container_name: "sales_analysis_db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sales_analysis_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "menu_service_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db:
    driver: local